### ISSUE TITLE
Logic 2 Testing

### ISSUE THREAD

**Issue by cashewpillar** [ralf-t/news-curation#2]
### Create Post Page:
- [Interface Requirement] Placeholders for title and content are missing
    - ![image](https://user-images.githubusercontent.com/65220389/137661424-6b42701f-4f92-4202-be69-3c77efbf1baa.png)

---
### Profile Page:
- [Suggestion] Reverse chronological order for posts
- [Interface][Temporary] Use small header:
    - ![image](https://user-images.githubusercontent.com/65220389/137661257-2c8e6389-f9f7-4985-8af1-82904825af7a.png)
    - ![image](https://user-images.githubusercontent.com/65220389/137658587-fd15c9da-3894-428c-a927-6909ac11b7be.png)

**Comment by arem-t-gh** [comment]
@xtian18 @jebjebs tag ko lang para astig
